{% set name = "pseudonetcdf" %}
{% set version = "3.0.2" %}
{% set sha256 = "6e26cb968c74b8ac03d3ee136fe7a24f8546f6ba5e62a204679b4fd9ad1a2d6d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/barronh/pseudonetcdf/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - pandas
    - netcdf4
    - scipy
    - pyyaml
    - matplotlib

test:
  imports:
    - PseudoNetCDF
    - PseudoNetCDF.test

about:
  home: http://github.com/barronh/pseudonetcdf
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'PseudoNetCDF like NetCDF except for many scientific format backends'
  doc_url: http://pseudonetcdf.readthedocs.io/
  dev_url: http://github.com/barronh/pseudonetcdf

extra:
  recipe-maintainers:
    - barronh
