{% set version = "3.2.0" %}

package:
  name: pseudonetcdf
  version: {{ version }}

source:
  url: http://github.com/barronh/pseudonetcdf/archive/v{{ version }}.tar.gz
  sha256: a783def7f4ae819f6184b604bd85c0f7e674a633f7a252d3b4e1ff52f45b8a48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - pandas
    - netcdf4
    - scipy
    - pyyaml
    - matplotlib-base

test:
  imports:
    - PseudoNetCDF
    - PseudoNetCDF.test

about:
  home: http://github.com/barronh/pseudonetcdf
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: PseudoNetCDF like NetCDF except for many scientific format backends
  doc_url: http://pseudonetcdf.readthedocs.io/
  dev_url: http://github.com/barronh/pseudonetcdf

extra:
  recipe-maintainers:
    - barronh
