travis:
  secure:
    BINSTAR_TOKEN: IcsMbFMiS2+136A4uHbao0Td+a2P/0aUbmU6fimVf0f29NiqqWN7UVUh+WjGFh+0g7BmTfGhSUIkAq7l/T6fl03djtDpqMMFuY812YeFheaT3WVlRMUIPpIm48VEk9orvL44Iwei7r8S3AdFXi6rVdNCbwPHZ/LWF5hP6dIhPMsYzxsqdtPPlFs8S1hy2wMy4nKXX0NwL/Pi7dCH5wWejxRpeOXIBm7FtJFChhCJgoml611nxSjebnJbmNefuXkOs0EruJavOvdTzC+mZ3TEMB8o7y+6NDn2nWTyFC30KeHooYQfg8PvPcx8B8OO6s8mq8AVS2ReE3rCtvkCxYYPlIkWiYshNr/cbV66Jv4z0uF/kdvZpdq985/jfaf9oKZiVVfBmD7Mz/9hIetLvau6M0mg0qIdTEuNFBNagLNYEkWcZHQJO2Yi95c7xwAI/DAri0WwmRjw7UTSoQfisppjRngMAJKz4tHL7vW5m/gg6HD8eP8i4pmLrBR0m2fA0HeKJdAymhal4jO8RvNjPDNh/MMI1+F4Z1HFKb4QiPPM2WfnG5bcUkUbYJWMeIJLn7EmwlLNLzIqPw7D49NwhexWcxCvELEUG4B1CgRz1WUH8teyzb/NrKHPuxQquqd8A2IVpjwW8XtEwYmD9vUekktwm7zRi0v9P9NVLyrcrD+K3fo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
